// =============================================================================
// FILE: types/api.types.ts
// PURPOSE: TypeScript interfaces that mirror the JSON shapes returned by the API.
//
// WHY TYPES MATTER IN API TESTING:
//   Without types, you write:  const title = body.titl  ← typo, no error!
//   With types, TypeScript says: Property 'titl' does not exist on type 'Post'
//
//   Types also act as living documentation — you can see exactly what fields
//   an API response contains without reading the API docs.
//
// WHERE THESE COME FROM:
//   JSONPlaceholder (https://jsonplaceholder.typicode.com) is a free fake REST
//   API used for prototyping and testing. These interfaces match its exact
//   response shapes, verified by reading the API output.
//
// UTILITY TYPES USED:
//   Omit<T, K>    → "T but without field K"
//   Partial<T>    → "T but every field is optional"
//   These let you derive related types from a base type without duplication.
// =============================================================================

// ---------------------------------------------------------------------------
// POST — /posts endpoint
// ---------------------------------------------------------------------------
export interface Post {
  id:     number;  // Auto-generated by the server (read-only after creation)
  userId: number;  // Foreign key — which user authored this post
  title:  string;  // Short headline of the post
  body:   string;  // Full text content of the post
}

// When CREATING a post (POST /posts), you don't supply the id — the server
// generates it. Omit<Post, 'id'> gives you { userId, title, body }.
export type CreatePostPayload = Omit<Post, 'id'>;

// When UPDATING a post (PATCH /posts/:id), all fields are optional because
// PATCH only changes what you send. Partial<> makes every field optional.
export type UpdatePostPayload = Partial<CreatePostPayload>;

// ---------------------------------------------------------------------------
// USER — /users endpoint
// A user has several nested objects (address, company) which are their own types.
// ---------------------------------------------------------------------------
export interface User {
  id:       number;  // Unique user identifier
  name:     string;  // Full display name (e.g. "Leanne Graham")
  username: string;  // Login handle (e.g. "Bret")
  email:    string;  // Contact email
  address:  Address; // Nested object — see below
  phone:    string;  // Contact phone number
  website:  string;  // Personal/company website
  company:  Company; // Nested object — see below
}

// Address is nested inside User — it has its own structure including geo coordinates
export interface Address {
  street:  string;  // Street name and number
  suite:   string;  // Apartment / suite number
  city:    string;  // City name
  zipcode: string;  // ZIP/postal code
  geo:     Geo;     // GPS coordinates — nested further
}

// Geographic coordinates — stored as strings (not numbers) in this API
export interface Geo {
  lat: string;  // Latitude  (e.g. "-37.3159")
  lng: string;  // Longitude (e.g. "81.1496")
}

// Company info nested inside User
export interface Company {
  name:        string;  // Company name
  catchPhrase: string;  // Company slogan
  bs:          string;  // Business description
}

// ---------------------------------------------------------------------------
// COMMENT — /comments endpoint
// Comments belong to Posts (postId is a foreign key linking them)
// ---------------------------------------------------------------------------
export interface Comment {
  id:     number;  // Unique comment identifier
  postId: number;  // Which post this comment belongs to (foreign key → Post.id)
  name:   string;  // Title/subject of the comment
  email:  string;  // Email of the commenter
  body:   string;  // Text content of the comment
}

// ---------------------------------------------------------------------------
// ALBUM — /albums endpoint
// Albums belong to Users (userId is a foreign key)
// ---------------------------------------------------------------------------
export interface Album {
  id:     number;  // Unique album identifier
  userId: number;  // Which user owns this album (foreign key → User.id)
  title:  string;  // Album title
}

// ---------------------------------------------------------------------------
// TODO — /todos endpoint
// ---------------------------------------------------------------------------
export interface Todo {
  id:        number;   // Unique todo identifier
  userId:    number;   // Which user owns this todo
  title:     string;   // Description of the task
  completed: boolean;  // true = done, false = pending
}

// ---------------------------------------------------------------------------
// ApiError — shape for error responses (not used by JSONPlaceholder but
// useful as a base type when connecting to real APIs that return error bodies)
// ---------------------------------------------------------------------------
export interface ApiError {
  message:    string;  // Human-readable error description
  statusCode: number;  // HTTP status code echoed in body
}
